-- Existing game data, votes, comments and guide posts are not modified.
create table if not exists public.build_posts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(user_id) on delete cascade,
  title text not null check (char_length(title) between 1 and 100),
  job_id text not null check (char_length(job_id) > 0),
  inventory_ids text[] not null check (cardinality(inventory_ids) = 6 and array_position(inventory_ids, null) is null and array_position(inventory_ids, '') is null),
  tags text[] not null check (cardinality(tags) between 1 and 5 and tags <@ array['보스','던전','회랑','PVP','예능']::text[]),
  content text not null check (char_length(content) between 1 and 5000),
  version text not null,
  created_at timestamptz not null default now()
);
create index if not exists build_posts_created_at_idx on public.build_posts(created_at desc);
alter table public.build_posts enable row level security;
drop policy if exists "Build posts are public" on public.build_posts;
create policy "Build posts are public" on public.build_posts for select using (true);
drop policy if exists "Users create own builds" on public.build_posts;
create policy "Users create own builds" on public.build_posts for insert to authenticated with check (auth.uid() = user_id);
drop policy if exists "Users delete own builds" on public.build_posts;
create policy "Users delete own builds" on public.build_posts for delete to authenticated using (auth.uid() = user_id);
grant select on public.build_posts to anon, authenticated;
grant insert, delete on public.build_posts to authenticated;
grant usage, select on sequence public.build_posts_id_seq to authenticated;
