create table if not exists public.guide_posts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(user_id) on delete cascade,
  title text not null check (char_length(title) between 1 and 100),
  content text not null check (char_length(content) between 1 and 10000),
  created_at timestamptz not null default now()
);

create index if not exists guide_posts_created_at_idx
  on public.guide_posts (created_at desc);

alter table public.guide_posts enable row level security;

drop policy if exists "Guide posts are public" on public.guide_posts;
create policy "Guide posts are public"
  on public.guide_posts for select
  using (true);

drop policy if exists "Users create own guide posts" on public.guide_posts;
create policy "Users create own guide posts"
  on public.guide_posts for insert to authenticated
  with check (auth.uid() = user_id);

drop policy if exists "Users delete own guide posts" on public.guide_posts;
create policy "Users delete own guide posts"
  on public.guide_posts for delete to authenticated
  using (auth.uid() = user_id);
