'use client';

import Link from 'next/link';
import { useEffect, useRef, useState, type ReactNode } from 'react';
import { Sword, Swords, WandSparkles, BowArrow, Flame, Zap, Hammer, Shield, Compass, Heart, Castle, Trees, Search, BookOpen, LayoutGrid, Trophy, Plus, X, GripVertical, MessageSquare, ThumbsUp, Check, Sparkles, Users, SlidersHorizontal, ChevronRight, Info, Download, Gem, PanelTop, Menu } from 'lucide-react';
import { guides, TIERS, VERSIONS, baseCounts, stats, type Entry, type Tier, type Category } from '@/lib/game-data';

import { CommunityPick } from '@/components/community-pick';
import { useCatalog } from '@/hooks/use-catalog';

type Page = 'home'|'database'|'tiers'|'builder'|'guides';
type Draft = {title:string;description:string;slots:Record<string,string>};
type Saved = Draft & {id:string;version:string};
type LocalData = {votes:Record<string,Tier>;likes:Record<string,boolean>;comments:Record<string,string[]>;drafts:Record<string,Draft>;saved:Saved[]};
const initial:LocalData={votes:{},likes:{},comments:{},drafts:{},saved:[]};
const storageKey='luminous-personal-v1';
const icons:Record<string,typeof Sword>={sword:Sword,swords:Swords,wand:WandSparkles,bow:BowArrow,flame:Flame,zap:Zap,hammer:Hammer,shield:Shield,compass:Compass,heart:Heart,castle:Castle,tree:Trees};
const navigation:{href:string;page:Page;label:string;icon:typeof Sword}[]=[{href:'/',page:'home',label:'홈',icon:PanelTop},{href:'/database/',page:'database',label:'데이터베이스',icon:LayoutGrid},{href:'/tiers/',page:'tiers',label:'티어리스트',icon:Trophy},{href:'/guides/',page:'guides',label:'공략',icon:BookOpen}];
const emptyDraft=():Draft=>({title:'나의 무기 티어리스트',description:'',slots:{}});
function Art({entry,small=false}:{entry:Entry;small?:boolean}) {const Icon=icons[entry.icon]||Sword;return <span key={entry.imageUrl||entry.id} className={`item-art element-${entry.element} ${small?'small':''}`} data-custom={!!entry.imageUrl}>{entry.imageUrl&&<img src={entry.imageUrl} alt={entry.name} onError={e=>{e.currentTarget.parentElement!.dataset.failed='true'}}/>}<Icon className="art-fallback" strokeWidth={1.3}/></span>}
function Badge({tier}:{tier:Tier}) {return <span className={`tier-badge tier-${tier}`}>{tier}</span>}
function Modal({title,onClose,children}:{title:string;onClose:()=>void;children:ReactNode}) {const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{const d=ref.current;d?.showModal();return()=>d?.close();},[]);return <dialog ref={ref} onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose();}} className="modal"><div className="modal-header"><h2>{title}</h2><button className="icon-button" onClick={onClose} aria-label="닫기"><X/></button></div>{children}</dialog>}

export function GuideApp({page}:{page:Page}) {
 const catalog=useCatalog();const entries=catalog.entries;
 const [version,setVersion]=useState('1.6');const [category,setCategory]=useState<Category>('무기');const [query,setQuery]=useState('');const [element,setElement]=useState('전체 속성');const [tab,setTab]=useState('커뮤니티 티어');const [local,setLocal]=useState<LocalData>(initial);const [ready,setReady]=useState(false);const [notice,setNotice]=useState('');const [selectedEntry,setSelected]=useState<Entry|null>(null);const [article,setArticle]=useState<typeof guides[number]|null>(null);const [showFormula,setShowFormula]=useState(false);const [menu,setMenu]=useState(false);const [sort,setSort]=useState('평균 점수순');const [comment,setComment]=useState('');const [viewSaved,setViewSaved]=useState<Saved|null>(null);
 const selected=selectedEntry?(entries.find(e=>e.id===selectedEntry.id)||selectedEntry):null;
 useEffect(()=>{if(new URLSearchParams(location.search).get('tab')==='users')setTab('유저 티어표')},[]);
 useEffect(()=>{try{const raw=window.localStorage.getItem(storageKey);if(raw){const parsed=JSON.parse(raw);if(parsed&&typeof parsed==='object'&&Array.isArray(parsed.saved))setLocal({...initial,...parsed});}const params=new URLSearchParams(location.search);const cat=params.get('category');if(['무기','직업','유물','던전'].includes(cat||''))setCategory(cat as Category);const v=params.get('version');if(VERSIONS.includes(v||''))setVersion(v!);const id=params.get('item');if(id)setSelected(entries.find(e=>e.id===id)||null);}catch{setNotice('저장한 데이터를 읽지 못했습니다. 이번 화면에서 계속 사용할 수 있습니다.');}setReady(true);},[]);
 useEffect(()=>{if(!ready)return;try{window.localStorage.setItem(storageKey,JSON.stringify(local));}catch{setNotice('브라우저 저장 공간을 사용할 수 없습니다. 변경 내용은 현재 화면에서만 유지됩니다.');}},[local,ready]);
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),4500);return()=>clearTimeout(t)},[notice]);
 const counts=(e:Entry)=>{const c=baseCounts(e,version);const vote=local.votes[`${version}:${e.id}`];if(vote)c[TIERS.indexOf(vote)]++;return c;};
 const result=(e:Entry)=>stats(counts(e));
 const filtered=entries.filter(e=>e.category===category&&(`${e.name} ${e.type}`).includes(query)&&(element==='전체 속성'||e.element===element)).sort((a,b)=>sort==='이름순'?a.name.localeCompare(b.name,'ko'):sort==='참여자순'?result(b).total-result(a).total:result(b).average-result(a).average);
 const vote=(e:Entry,t:Tier)=>{setLocal(d=>({...d,votes:{...d.votes,[`${version}:${e.id}`]:t}}));setNotice(`${e.name} · v${version} · ${t} 티어로 평가했습니다.`)};
 const draft=local.drafts[version]||emptyDraft();
 const updateDraft=(patch:Partial<Draft>)=>setLocal(d=>({...d,drafts:{...d.drafts,[version]:{...(d.drafts[version]||emptyDraft()),...patch}}}));
 const move=(id:string,t:string)=>{if(!entries.some(e=>e.id===id&&e.category==='무기')||!['미배치',...TIERS].includes(t))return;updateDraft({slots:{...draft.slots,[id]:t}});setNotice(`${entries.find(e=>e.id===id)?.name} → ${t}`)};
 const like=(key:string)=>setLocal(d=>({...d,likes:{...d.likes,[key]:!d.likes[key]}}));
 const openItem=(e:Entry)=>{setComment('');setSelected(e)};
 const totalVotes=entries.filter(e=>e.category==='무기').reduce((a,e)=>a+result(e).total,0);
 function ItemCard({entry:e}:{entry:Entry}) {const s=result(e);return <button className="item-card" onClick={()=>openItem(e)}><div className="card-art"><span className={`rarity rarity-${e.rarity}`}>{e.rarity}</span><Art entry={e}/><Badge tier={s.tier}/></div><div className="card-body"><span className="eyebrow">{e.type} <span>·</span> {e.element}</span><h3>{e.name}</h3><div className="card-meta"><strong>{s.average.toFixed(2)} <small>/ 5.00</small></strong><span><Users size={13}/> {s.total}</span></div></div></button>}
 function GuideCards(){return <div className="guide-grid">{guides.map((g,i)=>{const Icon=icons[g.icon];return <button className={`guide-card guide-${i}`} key={g.id} onClick={()=>{setArticle(g);setComment('')}}><div className="guide-art"><Icon strokeWidth={1}/><span>FIELD NOTES / 0{i+1}</span></div><div className="guide-copy"><span className="accent tiny">{g.tag}</span><h3>{g.title}</h3><p>{g.desc}</p><div className="guide-meta"><span>{g.author}</span><span>{g.time} 읽기</span></div></div></button>})}</div>}
 function Discussion({id,base=0}:{id:string;base?:number}) {return <section className="discussion"><div className="section-heading"><h3>모험가의 의견 <span className="muted">{(local.comments[id]||[]).length}</span></h3><button className={`subtle-button ${local.likes[id]?'liked':''}`} onClick={()=>like(id)} aria-pressed={!!local.likes[id]}><ThumbsUp size={15}/> 좋아요 {base+(local.likes[id]?1:0)}</button></div><p className="muted tiny">이 브라우저에만 저장되는 데모 댓글입니다.</p>{(local.comments[id]||[]).map((c,i)=><div className="comment" key={i}><span className="avatar">나</span><div><strong>방문 모험가</strong><p>{c}</p></div></div>)}{!(local.comments[id]||[]).length&&<p className="empty-mini">첫 의견을 남겨보세요.</p>}<form className="comment-form" onSubmit={e=>{e.preventDefault();const value=comment.trim();if(!value)return;setLocal(d=>({...d,comments:{...d.comments,[id]:[...(d.comments[id]||[]),value]}}));setComment('');setNotice('의견을 남겼습니다.')}}><input aria-label="댓글" maxLength={500} value={comment} onChange={e=>setComment(e.target.value)} placeholder="사용 경험이나 추천 조합을 남겨주세요"/><button className="primary" disabled={!comment.trim()}>등록</button></form></section>}
 return <div className="app-shell"><header className="header"><div className="header-inner"><Link href="/" className="brand"><span className="brand-mark"><Gem size={25}/></span><span>LUMINOUS<small>COMMUNITY ARCHIVE</small></span></Link><nav className={menu?'nav open':'nav'} aria-label="주 메뉴">{navigation.map(n=><Link key={n.page} className={page===n.page?'active':''} href={n.href} aria-current={page===n.page?'page':undefined}>{n.label}</Link>)}</nav><div className="header-right"><Link href="/builder/" className="primary compact"><Plus size={15}/> 티어표 만들기</Link><button className="icon-button mobile-menu" onClick={()=>setMenu(!menu)} aria-label="메뉴 열기" aria-expanded={menu}><Menu/></button></div></div></header>
 <main><div className="context-line"><span>루미너스 아카이브 <span className="slash">/</span> {page==='builder'?'나만의 티어표':navigation.find(n=>n.page===page)?.label}</span><span className="context-right"><label>게임 버전 <select aria-label="게임 버전" value={version} onChange={e=>setVersion(e.target.value)}>{VERSIONS.map(v=><option key={v} value={v}>v{v}{v==='1.6'?' · 최신':''}</option>)}</select></label></span></div>
 {catalog.error&&<div className="catalog-error" role="status">{catalog.error}<button className="text-button" onClick={()=>void catalog.refresh()}>다시 불러오기</button></div>}
 {page==='home'&&<><section className="home-intro"><div><div className="overline">THE ADVENTURER’S ARCHIVE</div><h1>더 나은 선택,<br/><span>함께 만드는 공략.</span></h1><p>무기를 탐색하고, 경험을 나누고.<br className="mobile-only"/> 당신의 한 표로 다음 모험을 준비하세요.</p><div className="hero-actions"><Link href="/tiers/" className="primary"><Trophy size={16}/> 커뮤니티 티어 보기</Link><Link href="/database/" className="secondary">데이터베이스 탐색</Link></div></div><CommunityPick weapons={entries.filter(e=>e.category==='무기')} version={version} isAdmin={catalog.isAdmin} blocked={!!selected||!!article||showFormula} result={result} renderArt={e=><Art entry={e}/>} onOpen={openItem} onSaved={e=>{catalog.update(e);setNotice('무기 이미지와 정보를 사이트에 저장했습니다.')}}/></section>
 <section className="section"><div className="section-heading"><div><span className="overline">EXPLORE THE ARCHIVE</span><h2>모험에 필요한 모든 정보</h2></div><Link href="/database/" className="text-button">전체 데이터 <ChevronRight size={16}/></Link></div><div className="category-grid">{([{name:'무기',icon:Swords,caption:'나에게 맞는 전투 스타일'},{name:'직업',icon:Shield,caption:'가능성을 여는 플레이'},{name:'유물',icon:Gem,caption:'빌드를 완성하는 조각'},{name:'던전',icon:Castle,caption:'다음 도전을 위한 준비'}] as const).map(c=><Link href={`/database/?category=${c.name}`} className="category-card" key={c.name}><span className="category-icon"><c.icon strokeWidth={1.5}/></span><div><h3>{c.name} <span>{entries.filter(e=>e.category===c.name).length.toString().padStart(2,'0')}</span></h3><p>{c.caption}</p></div><ChevronRight size={17}/></Link>)}</div></section>
 <div className="home-columns"><section className="section"><div className="section-heading"><div><span className="overline">COMMUNITY RANKING</span><h2>지금 주목받는 무기 <span className="small-tag">v{version}</span></h2></div><Link href="/tiers/" className="text-button">전체 티어 <ChevronRight size={16}/></Link></div><div className="item-grid home-items">{entries.slice(0,4).map(e=><ItemCard key={e.id} entry={e}/>)}</div></section><aside className="participation"><span className="overline">YOUR EXPERIENCE MATTERS</span><h2>티어표에<br/>당신의 경험을 더하세요.</h2><p>좋았던 무기, 아쉬웠던 무기.<br/>한 표가 더 나은 선택을 만듭니다.</p><div className="participation-number">{totalVotes.toLocaleString()}<span>개의 평가</span></div><Link href="/tiers/" className="secondary"><Users size={16}/> 평가에 참여하기</Link></aside></div>
 <section className="section"><div className="section-heading"><div><span className="overline">FIELD NOTES</span><h2>다음 모험을 위한 공략</h2></div><Link href="/guides/" className="text-button">모든 공략 <ChevronRight size={16}/></Link></div><GuideCards/></section></>}
 {page==='database'&&<><div className="page-title"><span className="overline">GAME DATABASE</span><h1>데이터베이스</h1><p>아이템의 특성과 모험가들의 평가를 한곳에서 확인하세요.</p></div><div className="tabs" role="tablist" aria-label="데이터 종류">{(['무기','직업','유물','던전'] as Category[]).map(c=><button key={c} role="tab" aria-selected={category===c} onClick={()=>{setCategory(c);setQuery('');setElement('전체 속성')}} className={category===c?'active':''}>{c} <span>{entries.filter(e=>e.category===c).length}</span></button>)}</div><div className="filters"><label className="search-field"><Search size={18}/><input aria-label="데이터 검색" placeholder={`${category} 이름으로 검색`} value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="속성 필터" value={element} onChange={e=>setElement(e.target.value)}>{['전체 속성','암흑','빛','냉기','화염','번개','대지','무속성'].map(e=><option key={e}>{e}</option>)}</select><select aria-label="정렬" value={sort} onChange={e=>setSort(e.target.value)}>{['평균 점수순','참여자순','이름순'].map(e=><option key={e}>{e}</option>)}</select></div><p className="result-count">{filtered.length}개의 {category} <span>· v{version} 커뮤니티 평가</span></p><div className="item-grid database-grid">{filtered.map(e=><ItemCard key={e.id} entry={e}/>)}</div>{!filtered.length&&<div className="empty"><Search/><h3>검색 결과가 없습니다</h3><p>다른 이름이나 속성으로 찾아보세요.</p><button className="secondary" onClick={()=>{setQuery('');setElement('전체 속성')}}>필터 초기화</button></div>}</>}
 {page==='tiers'&&<><div className="page-title title-with-action"><div><span className="overline">MADE BY ADVENTURERS</span><h1>함께 만드는 티어리스트</h1><p>하나의 정답보다, 수많은 경험. 나에게 맞는 선택을 찾아보세요.</p></div><Link href={`/builder/?version=${version}`} className="primary"><Plus size={17}/> 내 티어표 만들기</Link></div><div className="tabs" role="tablist" aria-label="티어표 종류">{['커뮤니티 티어','공략팀 티어','유저 티어표'].map(t=><button key={t} role="tab" aria-selected={tab===t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</div>
 {tab!=='유저 티어표'?<><div className="tier-toolbar"><div className="segmented">{(['무기','직업','유물'] as Category[]).map(c=><button className={category===c?'active':''} onClick={()=>setCategory(c)} key={c}>{c}</button>)}</div><button className="subtle-button" onClick={()=>setShowFormula(true)}><Info size={15}/> 산정 기준</button></div><div className="tier-summary"><div><Users/><span>{tab==='커뮤니티 티어'?'모험가의 평가':'공략팀의 선택'}<strong>{tab==='커뮤니티 티어'?entries.filter(e=>e.category===category).reduce((a,e)=>a+result(e).total,0).toLocaleString()+'표':'공략팀 기준'}</strong></span></div><p>{tab==='커뮤니티 티어'?'S~D 투표의 평균 점수로 구성됩니다. 카드에서 상세 분포를 확인하세요.':'기본 운용 난이도와 종합 활용도를 고려한 공략팀 평가입니다.'}<br/><small>v{version} · 종합 평가</small></p></div><div className="tier-board">{TIERS.map(t=><div className="tier-row" key={t}><div className={`tier-label tier-${t}`}><b>{t}</b><small>{({S:'4.50+',A:'3.50+',B:'2.50+',C:'1.50+',D:'1.00+'})[t]}</small></div><div className="tier-items">{entries.filter(e=>e.category===category&&(tab==='공략팀 티어'?(version==='1.6'?e.team:stats(baseCounts(e,version)).tier):result(e).tier)===t).map(e=><button className="tier-item" onClick={()=>openItem(e)} key={e.id}><Art entry={e} small/><div><strong>{e.name}</strong><span>{tab==='커뮤니티 티어'?result(e).average.toFixed(2)+' · '+result(e).total+'명':e.type+' · '+e.element}</span></div></button>)}{!entries.some(e=>e.category===category&&(tab==='공략팀 티어'?(version==='1.6'?e.team:stats(baseCounts(e,version)).tier):result(e).tier)===t)&&<span className="empty-row">아직 이 등급에 해당하는 항목이 없습니다.</span>}</div></div>)}</div><p className="footnote">{tab==='공략팀 티어'?'공략팀 티어는 공략팀 기준으로 관리되며 커뮤니티 투표와 별도로 표시됩니다.':'평균 점수가 같아도 평가 분포는 다를 수 있습니다. 상세 화면에서 의견 일치도를 함께 확인하세요.'}</p></>:<div className="user-tiers"><div className="section-heading"><h2>모험가의 관점 <span className="small-tag">v{version}</span></h2><span className="muted tiny">내 브라우저에 저장한 티어표</span></div>{local.saved.filter(s=>s.version===version).length?<div className="saved-grid">{local.saved.filter(s=>s.version===version).map(s=><button className="saved-card" key={s.id} onClick={()=>{setViewSaved(s);setComment('')}}><span className="accent tiny">개인 티어표 · v{s.version}</span><h3>{s.title}</h3><p>{s.description||'작성한 평가 기준이 없습니다.'}</p><div className="mini-board">{TIERS.map(t=><div key={t}><Badge tier={t}/><span>{entries.filter(e=>s.slots[e.id]===t).map(e=>e.name).join(' · ')||'—'}</span></div>)}</div></button>)}</div>:<div className="empty"><LayoutGrid/><h3>첫 번째 티어표를 만들어보세요</h3><p>저장한 티어표는 이 기기의 브라우저에서 확인할 수 있습니다.</p><Link className="primary" href={`/builder/?version=${version}`}>티어표 만들기</Link></div>}</div>}</>}
 {page==='builder'&&<><div className="page-title"><span className="overline">YOUR OWN PERSPECTIVE</span><h1>나만의 티어리스트</h1><p>무기를 끌어 놓거나 카드의 등급 선택 메뉴를 사용하세요. 변경 내용은 이 브라우저에 자동 저장됩니다.</p></div><div className="builder-meta"><label>티어표 제목<input disabled={!ready} maxLength={80} value={draft.title} onChange={e=>updateDraft({title:e.target.value})}/></label><label>평가 기준<input disabled={!ready} maxLength={180} placeholder="예: 보스전 · 풀강화 · 조작 난이도 고려" value={draft.description} onChange={e=>updateDraft({description:e.target.value})}/></label></div><div className="builder-toolbar"><span><GripVertical size={16}/> 무기 {entries.filter(e=>e.category==='무기'&&TIERS.includes(draft.slots[e.id] as Tier)).length} / 8 배치 <span className="small-tag">v{version}</span></span><button className="subtle-button" onClick={()=>{updateDraft({slots:{}});setNotice('무기를 모두 미배치로 옮겼습니다.')}}>배치 초기화</button></div><div className="tier-board builder-board">{[...TIERS,'미배치'].map(t=><div key={t} className="tier-row" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();move(e.dataTransfer.getData('text/plain'),t)}}><div className={`tier-label tier-${t}`}><b>{t}</b></div><div className="tier-items">{entries.filter(e=>e.category==='무기'&&(draft.slots[e.id]||'미배치')===t).map(e=><div className="builder-item" key={e.id} draggable onDragStart={event=>{event.dataTransfer.setData('text/plain',e.id);event.dataTransfer.effectAllowed='move'}}><Art entry={e} small/><span>{e.name}</span><select aria-label={`${e.name} 등급`} value={t} onChange={event=>move(e.id,event.target.value)}>{[...TIERS,'미배치'].map(v=><option key={v}>{v}</option>)}</select></div>)}{!entries.some(e=>e.category==='무기'&&(draft.slots[e.id]||'미배치')===t)&&<span className="empty-row">여기에 무기를 놓으세요</span>}</div></div>)}</div><div className="builder-bottom"><p><Check size={15}/> {ready?'현재 브라우저에 자동 저장':'불러오는 중'}</p><button className="primary" disabled={!ready||!draft.title.trim()} onClick={()=>{setLocal(d=>({...d,saved:[...d.saved,{...draft,title:draft.title.trim(),id:crypto.randomUUID(),version}]}));setNotice('유저 티어표에 저장했습니다.');}}>티어표 저장</button><Link href={`/tiers/?version=${version}&tab=users`} className="secondary">저장한 티어표 보기</Link></div><p className="footnote">온라인 게시·공유는 연결되지 않았습니다. 저장한 티어표 상세에서 JSON 파일로 내보낼 수 있습니다.</p></>}
 {page==='guides'&&<><div className="page-title"><span className="overline">FIELD NOTES</span><h1>모험가를 위한 공략</h1><p>장비 선택부터 던전 준비까지. 다음 도전의 실마리를 찾아보세요.</p></div><section className="section"><GuideCards/></section></>}
 </main><footer><Link href="/" className="footer-brand"><Gem size={18}/> LUMINOUS</Link><span>함께 기록하는 모험의 모든 것.</span><span>비공식 커뮤니티 팬 사이트</span></footer>
 {selected&&<Modal title={selected.name} onClose={()=>setSelected(null)}><div className="detail-intro"><Art entry={selected}/><div><span className="eyebrow">{selected.rarity} · {selected.category} · {selected.element}</span><h3>{selected.name} <Badge tier={result(selected).tier}/></h3><p>{selected.description}</p><span className="tiny muted">v{version} · {selected.type}</span></div></div><div className="detail-stats"><div><span>평균 점수</span><b>{result(selected).average.toFixed(2)}<small> / 5</small></b></div><div><span>의견 일치도</span><b>{result(selected).agreement}<small>%</small></b></div><div><span>평가 참여</span><b>{result(selected).total}<small>명</small></b></div></div><section className="vote-panel"><div className="section-heading"><h3>당신의 평가는?</h3><span className="small-tag">v{version} · 종합</span></div><div className="vote-buttons">{TIERS.map(t=><button key={t} disabled={!ready} className={`tier-${t} ${local.votes[`${version}:${selected.id}`]===t?'chosen':''}`} onClick={()=>vote(selected,t)} aria-pressed={local.votes[`${version}:${selected.id}`]===t}>{t}{local.votes[`${version}:${selected.id}`]===t&&<Check size={16}/>}</button>)}</div><p className="tiny muted">이 브라우저에서 항목·버전별 1표. 다시 선택하면 기존 평가가 변경됩니다.</p></section><section className="distribution"><div className="section-heading"><h3>평가 분포</h3><button className="text-button tiny" onClick={()=>setShowFormula(true)}>산정 기준</button></div>{counts(selected).map((c,i)=><div className="distribution-row" key={i}><b className={`text-${TIERS[i]}`}>{TIERS[i]}</b><div className="bar-track"><div className={`bar tier-${TIERS[i]}`} style={{width:`${c/result(selected).total*100}%`}}/></div><span>{Math.round(c/result(selected).total*100)}%</span><small>{c}표</small></div>)}</section><section className="related"><h3>함께 읽는 공략</h3><button onClick={()=>{setSelected(null);setArticle(guides[selected.id==='tower'?2:selected.id==='moonblade'?1:0]);setComment('')}}><BookOpen size={17}/>{guides[selected.id==='tower'?2:selected.id==='moonblade'?1:0].title}<ChevronRight size={15}/></button></section>{Discussion({id:`item:${version}:${selected.id}`})}</Modal>}
 {article&&<Modal title={article.tag} onClose={()=>setArticle(null)}><article className="article"><span className="overline">LUMINOUS FIELD NOTES</span><h1>{article.title}</h1><p className="muted tiny">{article.author} · {article.time} 읽기</p>{article.body.map((p,i)=><section key={i}><h3>0{i+1} · {['준비와 선택','실전에서 활용하기','다음 단계'][i]}</h3><p>{p}</p></section>)}</article>{Discussion({id:`guide:${article.id}`,base:article.likes})}</Modal>}
 {showFormula&&<Modal title="티어 산정 기준" onClose={()=>setShowFormula(false)}><div className="formula"><p>S=5, A=4, B=3, C=2, D=1로 환산한 가중 평균입니다.</p><p>S ≥ 4.50 / A ≥ 3.50 / B ≥ 2.50 / C ≥ 1.50 / D &lt; 1.50</p><p>의견 일치도 = (1 − 점수의 표준편차 ÷ 2) × 100. 모든 평가가 같으면 100%, S와 D에 반씩 나뉘면 0%입니다. 통계적 신뢰도를 의미하지 않습니다.</p><p>평가 데이터는 버전별로 분리되며, 공략팀 평가는 커뮤니티 결과와 별도로 관리합니다.</p><p className="muted">실제 서비스에서는 회원 인증, 중복 투표 방지, 최소 표본 수 및 서버 집계가 필요합니다.</p></div></Modal>}
 {viewSaved&&<Modal title={viewSaved.title} onClose={()=>setViewSaved(null)}><p className="saved-description">v{viewSaved.version} · {viewSaved.description||'종합 평가'}</p><div className="mini-board">{TIERS.map(t=><div key={t}><Badge tier={t}/><span>{entries.filter(e=>viewSaved.slots[e.id]===t).map(e=>e.name).join(' · ')||'미등록'}</span></div>)}</div><button className="secondary export" onClick={()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(viewSaved,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=`luminous-tier-${viewSaved.version}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setNotice('티어표 파일을 내보냈습니다.')}}><Download size={16}/> JSON 내보내기</button>{Discussion({id:`saved:${viewSaved.id}`})}</Modal>}
 {notice&&<div className="toast" role="status"><Check size={17}/>{notice}</div>}
 </div>
}


